/****************************************************************************
 * apps/packages/demos/contest2026_388_velaink/gcode.c
 *
 * 墨灵 VelaInk — G-code 生成
 *
 * 输出面向 GRBL 1.1f：G21/G90/G94，Z 轴抬落笔，笛卡尔坐标。
 * CoreXY 的运动学解算由下位控制板完成，本模块只负责"画什么"。
 *
 * SPDX-License-Identifier: Apache-2.0
 ****************************************************************************/

#include <math.h>
#include "gcode.h"

void velaink_machine_default(struct velaink_machine *m)
{
  m->width_mm      = 200.0f;  /* 大鱼 DayuWriter V2.21 Pro */
  m->height_mm     = 196.0f;
  m->margin_mm     = 10.0f;
  m->pen_up_mm     = 5.0f;
  m->pen_down_mm   = 0.0f;
  m->feed_mm_min   = 3000.0f;
  m->plunge_mm_min = 500.0f;
  m->safe_z_mm     = 5.0f;
}

void velaink_map_point(const struct velaink_machine *m,
                       float nx, float ny, float *mx, float *my)
{
  float usable_w = m->width_mm - 2.0f * m->margin_mm;
  float usable_h = m->height_mm - 2.0f * m->margin_mm;

  *mx = m->margin_mm + nx * usable_w;
  *my = m->margin_mm + ny * usable_h;
}

static int in_bounds(const struct velaink_machine *m, float x, float y)
{
  return (x >= -0.001f) && (x <= m->width_mm + 0.001f) &&
         (y >= -0.001f) && (y <= m->height_mm + 0.001f);
}

int velaink_gcode_emit(FILE *fp, const struct velaink_drawing *d,
                       const struct velaink_machine *m)
{
  int lines = 0;
  int s;

  if (!fp || !d || !m)
    {
      return -1;
    }

  /* ---- 文件头 ---- */

  fprintf(fp, "; VelaInk - AI creative writing robot\n");
  fprintf(fp, "; generated by openvela (contest2026_388_ajiejie)\n");
  fprintf(fp, "; workspace: %.0f x %.0f mm\n", (double)m->width_mm,
          (double)m->height_mm);
  fprintf(fp, "G21 ; millimeters\n");
  fprintf(fp, "G90 ; absolute positioning\n");
  fprintf(fp, "G94 ; units per minute feed\n");
  fprintf(fp, "G0 Z%.3f ; pen up\n", (double)m->safe_z_mm);
  fprintf(fp, "G0 X0.000 Y0.000 F%.0f ; home\n", (double)m->feed_mm_min);
  lines += 8;

  /* ---- 逐笔画输出 ---- */

  for (s = 0; s < d->nstrokes; s++)
    {
      const struct velaink_stroke *st = &d->strokes[s];
      int i;

      if (st->npts < 2)
        {
          continue;
        }

      for (i = 0; i < st->npts; i++)
        {
          float mx;
          float my;

          velaink_map_point(m, st->pts[i * 2], st->pts[i * 2 + 1], &mx, &my);

          if (!in_bounds(m, mx, my))
            {
              fprintf(fp, "; ERROR point out of bounds (%.2f, %.2f)\n",
                      (double)mx, (double)my);
              lines++;
              return -2;
            }

          if (i == 0)
            {
              /* 快速移动到起笔点上方 -> 落笔 */

              fprintf(fp, "G0 X%.3f Y%.3f\n", (double)mx, (double)my);
              fprintf(fp, "G1 Z%.3f F%.0f ; pen down\n",
                      (double)m->pen_down_mm, (double)m->plunge_mm_min);
              lines += 2;
            }
          else
            {
              fprintf(fp, "G1 X%.3f Y%.3f F%.0f\n", (double)mx, (double)my,
                      (double)m->feed_mm_min);
              lines++;
            }
        }

      /* 抬笔 */

      fprintf(fp, "G1 Z%.3f F%.0f ; pen up\n", (double)m->pen_up_mm,
              (double)m->plunge_mm_min);
      lines++;
    }

  /* ---- 收尾 ---- */

  fprintf(fp, "G0 Z%.3f\n", (double)m->safe_z_mm);
  fprintf(fp, "G0 X0.000 Y0.000 ; return to origin\n");
  fprintf(fp, "M30 ; program end\n");
  lines += 3;

  return lines;
}

int velaink_gcode_to_file(const char *path, const struct velaink_drawing *d,
                          const struct velaink_machine *m)
{
  FILE *fp;
  int   ret;

  fp = fopen(path, "w");
  if (!fp)
    {
      return -1;
    }

  ret = velaink_gcode_emit(fp, d, m);
  fclose(fp);
  return ret;
}
