############################################################################
# apps/packages/demos/contest2026_388_velaink/Makefile
#
# SPDX-License-Identifier: Apache-2.0
############################################################################

include $(APPDIR)/Make.defs

APPNAME = velaink
MAINSRC = velaink_main.c
CSRCS   = stroke.c gcode.c

include $(APPDIR)/Application.mk
